import QueryProvider from "@/providers/QueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Signika } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const signika = Signika({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-signika",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${signika.variable} !font-signika antialiased`}>
        <Toaster />
        <ReduxProvider>
          <QueryProvider>
            <Theme>{children}</Theme>
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
